def Kaufen_Anlageobjekte_websites():
    url_list = ["https://www.immobilienscout24.de/Suche/de/baden-wuerttemberg/anlageimmobilie",
                "https://www.immobilienscout24.de/Suche/de/bayern/anlageimmobilie",
                "https://www.immobilienscout24.de/Suche/de/berlin/berlin/anlageimmobilie",
                "https://www.immobilienscout24.de/Suche/de/brandenburg/anlageimmobilie",
                "https://www.immobilienscout24.de/Suche/de/bremen/anlageimmobilie",
                "https://www.immobilienscout24.de/Suche/de/hamburg/hamburg/anlageimmobilie",
                "https://www.immobilienscout24.de/Suche/de/hessen/anlageimmobilie",
                "https://www.immobilienscout24.de/Suche/de/niedersachsen/anlageimmobilie",
                "https://www.immobilienscout24.de/Suche/de/mecklenburg-vorpommern/anlageimmobilie",
                "https://www.immobilienscout24.de/Suche/de/nordrhein-westfalen/anlageimmobilie",
                "https://www.immobilienscout24.de/Suche/de/rheinland-pfalz/anlageimmobilie",
                "https://www.immobilienscout24.de/Suche/de/saarland/anlageimmobilie",
                "https://www.immobilienscout24.de/Suche/de/sachsen/anlageimmobilie",
                "https://www.immobilienscout24.de/Suche/de/sachsen-anhalt/anlageimmobilie",
                "https://www.immobilienscout24.de/Suche/de/schleswig-holstein/anlageimmobilie",
                "https://www.immobilienscout24.de/Suche/de/thueringen/anlageimmobilie"]

def Kaufen_Grundstuck_websites():
    url_list = ["https://www.immobilienscout24.de/Suche/de/baden-wuerttemberg/grundstueck-kaufen",
                "https://www.immobilienscout24.de/Suche/de/bayern/grundstueck-kaufen",
                "https://www.immobilienscout24.de/Suche/de/berlin/berlin/grundstueck-kaufen",
                "https://www.immobilienscout24.de/Suche/de/brandenburg/grundstueck-kaufen",
                "https://www.immobilienscout24.de/Suche/de/bremen/grundstueck-kaufen",
                "https://www.immobilienscout24.de/Suche/de/hamburg/hamburg/grundstueck-kaufen",
                "https://www.immobilienscout24.de/Suche/de/hessen/grundstueck-kaufen",
                "https://www.immobilienscout24.de/Suche/de/niedersachsen/grundstueck-kaufen",
                "https://www.immobilienscout24.de/Suche/de/mecklenburg-vorpommern/grundstueck-kaufen",
                "https://www.immobilienscout24.de/Suche/de/nordrhein-westfalen/grundstueck-kaufen",
                "https://www.immobilienscout24.de/Suche/de/rheinland-pfalz/grundstueck-kaufen",
                "https://www.immobilienscout24.de/Suche/de/saarland/grundstueck-kaufen",
                "https://www.immobilienscout24.de/Suche/de/sachsen/grundstueck-kaufen",
                "https://www.immobilienscout24.de/Suche/de/sachsen-anhalt/grundstueck-kaufen",
                "https://www.immobilienscout24.de/Suche/de/schleswig-holstein/grundstueck-kaufen",
                "https://www.immobilienscout24.de/Suche/de/thueringen/grundstueck-kaufen"]

def Kaufen_Haus_websites():
    url_list = [
            "https://www.immobilienscout24.de/Suche/de/baden-wuerttemberg/haus-kaufen",
            "https://www.immobilienscout24.de/Suche/de/bayern/haus-kaufen",
            "https://www.immobilienscout24.de/Suche/de/berlin/berlin/haus-kaufen",
            "https://www.immobilienscout24.de/Suche/de/brandenburg/haus-kaufen",
            "https://www.immobilienscout24.de/Suche/de/bremen/haus-kaufen",
            "https://www.immobilienscout24.de/Suche/de/hamburg/hamburg/haus-kaufen",
            "https://www.immobilienscout24.de/Suche/de/hessen/haus-kaufen",
            "https://www.immobilienscout24.de/Suche/de/niedersachsen/haus-kaufen",
            "https://www.immobilienscout24.de/Suche/de/mecklenburg-vorpommern/haus-kaufen",
            "https://www.immobilienscout24.de/Suche/de/nordrhein-westfalen/haus-kaufen",
            "https://www.immobilienscout24.de/Suche/de/rheinland-pfalz/haus-kaufen",
            "https://www.immobilienscout24.de/Suche/de/saarland/haus-kaufen",
            "https://www.immobilienscout24.de/Suche/de/sachsen/haus-kaufen",
            "https://www.immobilienscout24.de/Suche/de/sachsen-anhalt/haus-kaufen",
            "https://www.immobilienscout24.de/Suche/de/schleswig-holstein/haus-kaufen",
            "https://www.immobilienscout24.de/Suche/de/thueringen/haus-kaufen"

        ]

def Kaufen_Wohnungen_websites():
    url_list = ["https://www.immobilienscout24.de/Suche/de/baden-wuerttemberg/wohnung-kaufen",
                "https://www.immobilienscout24.de/Suche/de/bayern/wohnung-kaufen",
                "https://www.immobilienscout24.de/Suche/de/berlin/berlin/wohnung-kaufen",
                "https://www.immobilienscout24.de/Suche/de/brandenburg/wohnung-kaufen",
                "https://www.immobilienscout24.de/Suche/de/bremen/wohnung-kaufen",
                "https://www.immobilienscout24.de/Suche/de/hamburg/hamburg/wohnung-kaufen",
                "https://www.immobilienscout24.de/Suche/de/hessen/wohnung-kaufen",
                "https://www.immobilienscout24.de/Suche/de/niedersachsen/wohnung-kaufen",
                "https://www.immobilienscout24.de/Suche/de/mecklenburg-vorpommern/wohnung-kaufen",
                "https://www.immobilienscout24.de/Suche/de/nordrhein-westfalen/wohnung-kaufen",
                "https://www.immobilienscout24.de/Suche/de/rheinland-pfalz/wohnung-kaufen",
                "https://www.immobilienscout24.de/Suche/de/saarland/wohnung-kaufen",
                "https://www.immobilienscout24.de/Suche/de/sachsen/wohnung-kaufen",
                "https://www.immobilienscout24.de/Suche/de/sachsen-anhalt/wohnung-kaufen",
                "https://www.immobilienscout24.de/Suche/de/schleswig-holstein/wohnung-kaufen",
                "https://www.immobilienscout24.de/Suche/de/thueringen/wohnung-kaufen"]

def Mieten_Wohnungen_websites():
    url_list = ["https://www.immobilienscout24.de/Suche/de/berlin/berlin/wohnung-mieten",
                "https://www.immobilienscout24.de/Suche/de/bayern/wohnung-mieten",
                "https://www.immobilienscout24.de/Suche/de/brandenburg/wohnung-mieten",
                "https://www.immobilienscout24.de/Suche/de/bremen/wohnung-mieten",
                "https://www.immobilienscout24.de/Suche/de/hamburg/hamburg/wohnung-mieten",
                "https://www.immobilienscout24.de/Suche/de/hessen/wohnung-mieten",
                "https://www.immobilienscout24.de/Suche/de/niedersachsen/wohnung-mieten",
                "https://www.immobilienscout24.de/Suche/de/mecklenburg-vorpommern/wohnung-mieten",
                "https://www.immobilienscout24.de/Suche/de/nordrhein-westfalen/wohnung-mieten",
                "https://www.immobilienscout24.de/Suche/de/rheinland-pfalz/wohnung-mieten",
                "https://www.immobilienscout24.de/Suche/de/saarland/wohnung-mieten",
                "https://www.immobilienscout24.de/Suche/de/sachsen/wohnung-mieten",
                "https://www.immobilienscout24.de/Suche/de/sachsen-anhalt/wohnung-mieten",
                "https://www.immobilienscout24.de/Suche/de/schleswig-holstein/wohnung-mieten",
                "https://www.immobilienscout24.de/Suche/de/thueringen/wohnung-mieten"]
